
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package daydayup_openstock_cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 3;
  public static final int NUMBER = 9;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int DIV = 5;
  public static final int error = 1;
  public static final int AT = 8;
  public static final int RPAREN = 7;
  public static final int IDENTIFIER = 10;
  public static final int TIMES = 4;
  public static final int LPAREN = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "LPAREN",
  "RPAREN",
  "AT",
  "NUMBER",
  "IDENTIFIER"
  };
}

